version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    container_name: tournament-dynamodb
    ports:
      - "8000:8000"
    networks:
      - tournament-mongodb-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - tournament-mongodb-network

  tournament:
    image: openjdk:8-jre
    container_name: tournament
    volumes:
      - ./build/libs/tournament-1.0-SNAPSHOT-all.jar:/backend/tournament-1.0.0-SNAPSHOT.jar
      - ./src/main/resources/application.yml:/backend/application.yml
    working_dir: /backend
    command: ["java", "-jar", "tournament-1.0.0-SNAPSHOT.jar", "server", "application.yml"]
    ports:
      - "8090:8080"
      - "8081:8081"
    environment:
      AWS_REGION: eu-west1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    networks:
      - tournament-mongodb-network

networks:
  tournament-mongodb-network: