server:
  maxThreads: 512
  applicationContextPath: /tournament
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

dynamoDBConnection:
  credentials:
    username: "usr_tournament"
    password: "b3tcl1c"
  seeds:
    - host: "tournament-dynamodb"
      port: 8000
  database: "tournament"

swagger:
  resourcePackage: com.yabaa.tournament.resources
  basePath: /tournament
  title: "Player API"
  version: v1
  description: "A simple API used to expose API operations on Player MongoDB collection"
  scan: true
