server:
  maxThreads: 512
  applicationContextPath: /tournament
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

dynamoDBConnection:
  host: "tournament-dynamodb"
  port: 8000

swagger:
  resourcePackage: com.yabaa.tournament.resources
  basePath: /tournament
  title: "Tournament API"
  version: v1
  description: "A simple API used to expose API operations on Player DynamoDB collection"
  scan: true
